# Generated by Django 4.1 on 2022-08-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "description",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=22, null=True)),
                ("status", models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
